AWSTemplateFormatVersion: 2010-09-09

Parameters:
  pMonitoringEventBusArn:
    Description: The arn of the monitoring account event bus
    Type: String
  EnableSageMakerProcessingJobEventsStreaming:
    Type: String
    Default: Yes
    AllowedValues:
      - Yes
      - No
    Description: Enable SageMaker processing job events streamed to centralized monitoring account eventbus
  EnableSageMakerTrainingJobEventsStreaming:
    Type: String
    Default: Yes
    AllowedValues:
      - Yes
      - No
    Description: Enable SageMaker training job events streamed to centralized monitoring account eventbus
  EnableSageMakerPipelineExecutionEventsStreaming:
    Type: String
    Default: Yes
    AllowedValues:
      - Yes
      - No
    Description: Enable SageMaker pipeline execution events streamed to centralized monitoring account eventbus
  EnableSageMakerPipelineStepStatusEventsStreaming:
    Type: String
    Default: Yes
    AllowedValues:
      - Yes
      - No
    Description: Enable SageMaker pipeline execution step status events streamed to centralized monitoring account eventbus
  
Conditions:
  ProcessingJobLoggingEnabled: !Equals [!Ref EnableSageMakerProcessingJobEventsStreaming, Yes]
  TrainingJobLoggingEnabled: !Equals [!Ref EnableSageMakerTrainingJobEventsStreaming, Yes]
  PipelineExecutionLoggingEnabled: !Equals [!Ref EnableSageMakerPipelineExecutionEventsStreaming, Yes]
  PipelineStepStatusLoggingEnabled: !Equals [!Ref EnableSageMakerPipelineStepStatusEventsStreaming, Yes]

Resources:
  crossAccountToMonitoringAccountEventbusRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
        Version: "2012-10-17"
  crossAccountToMonitoringAccountEventbusRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: events:PutEvents
            Effect: Allow
            Resource: !Ref pMonitoringEventBusArn
        Version: "2012-10-17"
      PolicyName: crossAccountToMonitoringAccountEventbusRolePolicy
      Roles:
        - Ref: crossAccountToMonitoringAccountEventbusRole

  sageMakerAPIEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: SageMaker service API events streamed to centralized monitoring account eventbus
      EventPattern:
        source:
          - aws.sagemaker
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - sagemaker.amazonaws.com
      State: ENABLED
      Targets:
        - Arn: !Ref pMonitoringEventBusArn
          Id: Target1
          RoleArn:
            Fn::GetAtt:
              - crossAccountToMonitoringAccountEventbusRole
              - Arn

  sageMakerProcessingJobEventRule:
    Condition: ProcessingJobLoggingEnabled
    Type: AWS::Events::Rule
    Properties:
      Description: SageMaker Processing Job State Change event streamed to centralized monitoring account eventbus
      EventPattern:
        source:
          - aws.sagemaker
        detail-type:
          - SageMaker Processing Job State Change
      State: ENABLED
      Targets:
        - Arn: !Ref pMonitoringEventBusArn
          Id: Target1
          RoleArn:
            Fn::GetAtt:
              - crossAccountToMonitoringAccountEventbusRole
              - Arn

  sageMakerTrainingJobEventRule:
    Condition: TrainingJobLoggingEnabled
    Type: AWS::Events::Rule
    Properties:
      Description: SageMaker Training Job State Change event streamed to centralized monitoring account eventbus
      EventPattern:
        source:
          - aws.sagemaker
        detail-type:
          - SageMaker Training Job State Change
      State: ENABLED
      Targets:
        - Arn: !Ref pMonitoringEventBusArn
          Id: Target1
          RoleArn:
            Fn::GetAtt:
              - crossAccountToMonitoringAccountEventbusRole
              - Arn
  
  sageMakerPipelineExecutionEventRule:
    Condition: PipelineExecutionLoggingEnabled
    Type: AWS::Events::Rule
    Properties:
      Description: SageMaker Pipeline Execution State Change event streamed to centralized monitoring account eventbus
      EventPattern:
        source:
          - aws.sagemaker
        detail-type:
          - SageMaker Model Building Pipeline Execution Status Change
      State: ENABLED
      Targets:
        - Arn: !Ref pMonitoringEventBusArn
          Id: Target1
          RoleArn:
            Fn::GetAtt:
              - crossAccountToMonitoringAccountEventbusRole
              - Arn
  
  sageMakerPipelineStepStatusEventRule:
    Condition: PipelineStepStatusLoggingEnabled
    Type: AWS::Events::Rule
    Properties:
      Description: SageMaker Pipeline Execution Step Status Change event streamed to centralized monitoring account eventbus
      EventPattern:
        source:
          - aws.sagemaker
        detail-type:
          - SageMaker Model Building Pipeline Execution Step Status Change
      State: ENABLED
      Targets:
        - Arn: !Ref pMonitoringEventBusArn
          Id: Target1
          RoleArn:
            Fn::GetAtt:
              - crossAccountToMonitoringAccountEventbusRole
              - Arn