Parameters:
  Prefix:
    Type: String
    Default: sagemaker-monitoring
  EnableSageMakerProcessingJobLogging:
    Type: String
    Default: Yes
    AllowedValues:
      - Yes
      - No
    Description: Enable SageMaker processing job events streamed to log group
  EnableSageMakerTrainingJobLogging:
    Type: String
    Default: No
    AllowedValues:
      - Yes
      - No
    Description: Enable SageMaker training job events streamed to log group
  SagemakerJobNamePattern:
    Type: String
    Default: /(?<job_prefix>S+)-(?<job_time>d{4}-d{2}-d{2}-d{2}-d{2})/

Conditions:
  ProcessingJobLoggingEnabled: !Equals [!Ref EnableSageMakerProcessingJobLogging, Yes]
  TrainingJobLoggingEnabled: !Equals [!Ref EnableSageMakerTrainingJobLogging, Yes]

Resources:
  sageMakerProcessingJobEventRule:
    Condition: ProcessingJobLoggingEnabled
    Type: AWS::Events::Rule
    Properties:
      Description: SageMaker Processing Job State Change event streamed to a log group
      EventPattern:
        source:
          - aws.sagemaker
        detail-type:
          - SageMaker Processing Job State Change
      State: ENABLED
      Targets:
        - Arn:
            Fn::Join:
              - ""
              - - "arn:"
                - Ref: AWS::Partition
                - ":logs:"
                - Ref: AWS::Region
                - ":"
                - Ref: AWS::AccountId
                - ":log-group:"
                - Ref: sageMakerProcessingJobLogGroup
          Id: Target0

  sageMakerProcessingJobLogGroup:
    Condition: ProcessingJobLoggingEnabled
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${Prefix}/sagemaker-processing-job-state
      RetentionInDays: 731

  sageMakerTrainingJobEventRule:
    Condition: TrainingJobLoggingEnabled
    Type: AWS::Events::Rule
    Properties:
      Description: SageMaker Training Job State Change event streamed to a log group
      EventPattern:
        source:
          - aws.sagemaker
        detail-type:
          - SageMaker Training Job State Change
      State: ENABLED
      Targets:
        - Arn:
            Fn::Join:
              - ""
              - - "arn:"
                - Ref: AWS::Partition
                - ":logs:"
                - Ref: AWS::Region
                - ":"
                - Ref: AWS::AccountId
                - ":log-group:"
                - Ref: sageMakerTrainingJobLogGroup
          Id: Target0

  sageMakerTrainingJobLogGroup:
    Condition: TrainingJobLoggingEnabled
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${Prefix}/sagemaker-training-job-state
      RetentionInDays: 731

  CloudWatchLogsResourcePolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: "AllowEventBridgeToPutLogEvents"
      PolicyDocument: '{"Statement":[{"Action":["logs:PutLogEvents"],"Effect":"Allow","Principal":{"Service":"events.amazonaws.com"},"Resource":"*"}],"Version":"2012-10-17"}'

  sagemakerMonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardBody:
        Fn::Join:
          - ""
          - - '{"widgets":[{"type":"log","width":6,"height":6,"x":0,"y":0,"properties":{"view":"table","region":"'
            - Ref: AWS::Region
            - "\",\"query\":\"SOURCE '"
            - Ref: sageMakerProcessingJobLogGroup
            - "' | sort @timestamp desc\\n| filter detail.ProcessingJobStatus like /Completed/\\n| fields detail.ProcessingJobName as job_name, detail.ProcessingJobStatus as job_status, fromMillis(detail.ProcessingStartTime) as start_time, fromMillis(detail.ProcessingEndTime) as end_time\\n| parse detail.ProcessingJobName "
            - Ref: SagemakerJobNamePattern
            - "\"}},{\"type\":\"log\",\"width\":6,\"height\":6,\"x\":0,\"y\":6,\"properties\":{\"view\":\"timeSeries\",\"region\":\""
            - Ref: AWS::Region
            - "\",\"query\":\"SOURCE '"
            - Ref: sageMakerProcessingJobLogGroup
            - "' | filter detail.ProcessingJobStatus like /Completed/\\n| parse detail.ProcessingJobName "
            - Ref: SagemakerJobNamePattern
            - "\\n| display detail.ProcessingJobName, detail.ProcessingJobStatus, fromMillis(detail.ProcessingStartTime) as start_time, fromMillis(detail.ProcessingEndTime) as end_time\\n| stat count(*) as completed_jobs by job_prefix\",\"stacked\":false}},{\"type\":\"log\",\"width\":6,\"height\":6,\"x\":0,\"y\":12,\"properties\":{\"view\":\"timeSeries\",\"region\":\""
            - Ref: AWS::Region
            - "\",\"query\":\"SOURCE '"
            - Ref: sageMakerProcessingJobLogGroup
            - "' | filter detail.ProcessingJobStatus like /Completed/\\n| display detail.ProcessingJobName, detail.ProcessingJobStatus\\n| sort @timestamp desc\",\"stacked\":false}}]}"
      DashboardName: !Sub ${Prefix}-Dashboard

