Parameters:
  Prefix:
    Type: String
    Default: sagemaker-monitoring
  EnableSageMakerProcessingJobLogging:
    Type: String
    Default: Yes
    AllowedValues:
      - Yes
      - No
    Description: Enable SageMaker processing job events streamed to log group
  EnableSageMakerTrainingJobLogging:
    Type: String
    Default: No
    AllowedValues:
      - Yes
      - No
    Description: Enable SageMaker training job events streamed to log group
  EnableSageMakerPipelineExecutionLogging:
    Type: String
    Default: Yes
    AllowedValues:
      - Yes
      - No
    Description: Enable SageMaker pipeline execution events streamed to log group
  EnableSageMakerPipelineStepStatusLogging:
    Type: String
    Default: Yes
    AllowedValues:
      - Yes
      - No
    Description: Enable SageMaker pipeline execution step status events streamed to log group
  SagemakerJobNamePattern:
    Type: String
    Default: /(?<job_prefix>S+)-(?<job_time>d{4}-d{2}-d{2}-d{2}-d{2})/
  CloudWatchLogsRetentionInDays:
    Description: The number of days log events are kept in CloudWatch Logs
    Type: Number
    Default: 731
    AllowedValues:
      [
        1,
        3,
        5,
        7,
        14,
        30,
        60,
        90,
        120,
        150,
        180,
        365,
        400,
        545,
        731,
        1827,
        3653,
      ]

Conditions:
  ProcessingJobLoggingEnabled: !Equals [!Ref EnableSageMakerProcessingJobLogging, Yes]
  TrainingJobLoggingEnabled: !Equals [!Ref EnableSageMakerTrainingJobLogging, Yes]
  PipelineExecutionLoggingEnabled: !Equals [!Ref EnableSageMakerPipelineExecutionLogging, Yes]
  PipelineStepStatusLoggingEnabled: !Equals [!Ref EnableSageMakerPipelineStepStatusLogging, Yes]

Resources:
  sageMakerProcessingJobEventRule:
    Condition: ProcessingJobLoggingEnabled
    Type: AWS::Events::Rule
    Properties:
      Description: SageMaker Processing Job State Change event streamed to a log group
      EventPattern:
        source:
          - aws.sagemaker
        detail-type:
          - SageMaker Processing Job State Change
      State: ENABLED
      Targets:
        - Arn:
            Fn::Join:
              - ""
              - - "arn:"
                - Ref: AWS::Partition
                - ":logs:"
                - Ref: AWS::Region
                - ":"
                - Ref: AWS::AccountId
                - ":log-group:"
                - Ref: sageMakerProcessingJobLogGroup
          Id: Target0

  sageMakerProcessingJobLogGroup:
    Condition: ProcessingJobLoggingEnabled
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${Prefix}/sagemaker-processing-job-state
      RetentionInDays: !Ref CloudWatchLogsRetentionInDays

  sageMakerTrainingJobEventRule:
    Condition: TrainingJobLoggingEnabled
    Type: AWS::Events::Rule
    Properties:
      Description: SageMaker Training Job State Change event streamed to a log group
      EventPattern:
        source:
          - aws.sagemaker
        detail-type:
          - SageMaker Training Job State Change
      State: ENABLED
      Targets:
        - Arn:
            Fn::Join:
              - ""
              - - "arn:"
                - Ref: AWS::Partition
                - ":logs:"
                - Ref: AWS::Region
                - ":"
                - Ref: AWS::AccountId
                - ":log-group:"
                - Ref: sageMakerTrainingJobLogGroup
          Id: Target0

  sageMakerTrainingJobLogGroup:
    Condition: TrainingJobLoggingEnabled
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${Prefix}/sagemaker-training-job-state
      RetentionInDays: !Ref CloudWatchLogsRetentionInDays

  sageMakerPipelineExecutionEventRule:
    Condition: PipelineExecutionLoggingEnabled
    Type: AWS::Events::Rule
    Properties:
      Description: SageMaker Pipeline Execution State Change event streamed to a log group
      EventPattern:
        source:
          - aws.sagemaker
        detail-type:
          - SageMaker Model Building Pipeline Execution Status Change
      State: ENABLED
      Targets:
        - Arn:
            Fn::Join:
              - ""
              - - "arn:"
                - Ref: AWS::Partition
                - ":logs:"
                - Ref: AWS::Region
                - ":"
                - Ref: AWS::AccountId
                - ":log-group:"
                - Ref: sageMakerPipelineExecutionLogGroup
          Id: Target0

  sageMakerPipelineExecutionLogGroup:
    Condition: PipelineExecutionLoggingEnabled
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${Prefix}/sagemaker-pipeline-execution-state
      RetentionInDays: !Ref CloudWatchLogsRetentionInDays

  sageMakerPipelineStepStatusEventRule:
    Condition: PipelineStepStatusLoggingEnabled
    Type: AWS::Events::Rule
    Properties:
      Description: SageMaker Pipeline Execution Step Status Change event streamed to a log group
      EventPattern:
        source:
          - aws.sagemaker
        detail-type:
          - SageMaker Model Building Pipeline Execution Step Status Change
      State: ENABLED
      Targets:
        - Arn:
            Fn::Join:
              - ""
              - - "arn:"
                - Ref: AWS::Partition
                - ":logs:"
                - Ref: AWS::Region
                - ":"
                - Ref: AWS::AccountId
                - ":log-group:"
                - Ref: sageMakerPipelineStepLogGroup
          Id: Target0

  sageMakerPipelineStepLogGroup:
    Condition: PipelineStepStatusLoggingEnabled
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${Prefix}/sagemaker-pipeline-step-state
      RetentionInDays: !Ref CloudWatchLogsRetentionInDays

  CloudWatchLogsResourcePolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: "AllowEventBridgeToPutLogEvents"
      PolicyDocument: '{"Statement":[{"Action":["logs:PutLogEvents"],"Effect":"Allow","Principal":{"Service":"events.amazonaws.com"},"Resource":"*"}],"Version":"2012-10-17"}'

  sagemakerMonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardBody:
        Fn::Join:
          - ""
          - - '{"widgets":[{"type":"log","width":6,"height":6,"x":0,"y":0,"properties":{"view":"table","title":"SageMaker Processing Job History","region":"'
            - Ref: AWS::Region
            - "\",\"query\":\"SOURCE '"
            - Ref: sageMakerProcessingJobLogGroup
            - "' | sort @timestamp desc\\n| filter detail.ProcessingJobStatus not like /InProgress/\\n| fields detail.ProcessingJobName as jobname,  detail.ProcessingJobStatus as status, fromMillis(detail.ProcessingStartTime) as start_time, (detail.ProcessingEndTime-detail.ProcessingStartTime)/1000 as duration_in_seconds, detail.FailureReason as failure_reason\"}},{\"type\":\"log\",\"width\":6,\"height\":6,\"x\":0,\"y\":6,\"properties\":{\"view\":\"table\",\"title\":\"SageMaker Training Job History\",\"region\":\""
            - Ref: AWS::Region
            - "\",\"query\":\"SOURCE '"
            - Ref: sageMakerTrainingJobLogGroup
            - "' | sort @timestamp desc\\n| filter detail.TrainingJobStatus not like /InProgress/\\n| fields detail.TrainingJobName as jobname,  detail.TrainingJobStatus as status, detail.SecondaryStatus as secondary_status, fromMillis(detail.TrainingStartTime) as start_time, (detail.TrainingEndTime-detail.TrainingStartTime)/1000 as duration_in_seconds\"}}]}"
      DashboardName: !Sub ${Prefix}-Dashboard

