on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        options:
          - dev
        default: 'default'

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        if: inputs.environment == 'dev'
        run: echo  The environment is ${{ inputs.environment }} 
      - name: default env
        if: inputs.environment == 'default'
        run: echo Default envrionment